ERROR - 2023-06-21 14:28:27 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'db_siera', 3306, '', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `distrit...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\siera\app\Controllers\Distrito.php(22): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Distrito->listar()
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Distrito))
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `distrit...', Array, false)
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\siera\app\Controllers\Distrito.php(22): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Distrito->listar()
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Distrito))
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-06-21 14:28:27 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'db_siera', 3306, '', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\siera\app\Controllers\Provincia.php(20): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Provincia->listar()
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Provincia))
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\siera\app\Controllers\Provincia.php(20): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Provincia->listar()
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Provincia))
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-06-21 14:28:27 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'db_siera', 3306, '', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\siera\app\Controllers\Ejecutora.php(20): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Ejecutora->listar()
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ejecutora))
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\siera\app\Controllers\Ejecutora.php(20): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Ejecutora->listar()
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ejecutora))
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-06-21 14:28:27 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'db_siera', 3306, '', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `iiee`.*...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\siera\app\Controllers\Iiee.php(68): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Iiee->listar()
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Iiee))
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `iiee`.*...', Array, false)
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\siera\app\Controllers\Iiee.php(68): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Iiee->listar()
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Iiee))
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-06-21 14:28:27 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `distrito`.*, `provincia`.`descripcion` as `nombreProvincia`
FROM `distrito`
JOIN `provincia` ON `provincia`.`idprovincia` = `distrito`.`provincia_idprovincia`', [], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Distrito.php(22): CodeIgniter\Model->__call('get', [])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Distrito->listar()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Distrito))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 14:28:27 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `provincia`', [], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Provincia.php(20): CodeIgniter\Model->__call('get', [])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Provincia->listar()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Provincia))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 14:28:27 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `iiee`.*, `ejecutora`.`descripcion` as `nombreEjecutora`, `provincia`.`descripcion` as `nombreProvincia`, `distrito`.`descripcion` as `nombreDistrito`
FROM `iiee`
JOIN `ejecutora` ON `ejecutora`.`idejecutora` = `iiee`.`ejecutora_idejecutora`
JOIN `provincia` ON `provincia`.`idprovincia` = `iiee`.`provincia_idprovincia`
JOIN `distrito` ON `distrito`.`iddistrito` = `iiee`.`distrito_iddistrito`', [], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Iiee.php(68): CodeIgniter\Model->__call('get', [])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Iiee->listar()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Iiee))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 14:28:27 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ejecutora`', [], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Ejecutora.php(20): CodeIgniter\Model->__call('get', [])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Ejecutora->listar()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ejecutora))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 17:55:06 --> Class 'App\Models\M_director' not found
in APPPATH\Controllers\Director.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\Director->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 17:56:31 --> Class 'App\Models\M_director' not found
in APPPATH\Controllers\Director.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\Director->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 17:56:34 --> Class 'App\Models\M_director' not found
in APPPATH\Controllers\Director.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\Director->__construct()
 2 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 20:57:41 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\siera\app\Controllers\Director.php(39): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->registrar()
#9 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#10 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-06-21 20:57:41 --> Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (:usuario:, :contraseña:, :estado:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Director.php(39): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->registrar()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 20:59:02 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\siera\app\Controllers\Director.php(39): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->registrar()
#9 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#10 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-06-21 20:59:02 --> Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (:usuario:, :contraseña:, :estado:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Director.php(39): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->registrar()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 20:59:41 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\siera\app\Controllers\Director.php(40): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->registrar()
#9 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#10 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-06-21 20:59:41 --> Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (:usuario:, :contraseña:, :estado:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Director.php(40): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->registrar()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 21:01:14 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\siera\app\Controllers\Director.php(40): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->registrar()
#9 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#10 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-06-21 21:01:14 --> Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (:usuario:, :contraseña:, :estado:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Director.php(40): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->registrar()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 21:02:50 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\siera\app\Controllers\Director.php(40): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->registrar()
#9 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#10 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-06-21 21:02:50 --> Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (:usuario:, :contraseña:, :estado:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Director.php(40): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->registrar()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 21:03:29 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\siera\app\Controllers\Director.php(40): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->registrar()
#9 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#10 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-06-21 21:03:29 --> Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'admin\', \'123456\', \'activo\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (:usuario:, :contraseña:, :estado:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Director.php(40): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->registrar()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 21:05:07 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\siera\app\Controllers\Director.php(40): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->registrar()
#9 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#10 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-06-21 21:05:07 --> Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'aaaaaaaaaa\', \'123456\', \'activo\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'aaaaaaaaaa\', \'123456\', \'activo\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'aaaaaaaaaa\', \'123456\', \'activo\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (:usuario:, :contraseña:, :estado:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Director.php(40): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->registrar()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 21:06:08 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\siera\app\Controllers\Director.php(40): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->registrar()
#9 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#10 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-06-21 21:06:08 --> Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'aaaaaaaaaa\', \'123456\', \'activo\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'aaaaaaaaaa\', \'123456\', \'activo\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (\'aaaaaaaaaa\', \'123456\', \'activo\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`usuario`, `contraseña`, `estado`) VALUES (:usuario:, :contraseña:, :estado:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Director.php(40): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->registrar()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-21 21:39:40 --> mysqli_sql_exception: Unknown column 'idejecutora' in 'where clause' in C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\siera\app\Controllers\Director.php(75): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Director->eliminar()
#7 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
#8 C:\xampp\htdocs\siera\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\siera\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-06-21 21:39:40 --> Unknown column 'idejecutora' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *
FROM `director`
WHERE `idejecutora` = \'2\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `director`
WHERE `idejecutora` = \'2\'')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `director`
WHERE `idejecutora` = \'2\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `director`
WHERE `idejecutora` = :idejecutora:', [...], false)
 5 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Director.php(75): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->eliminar()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:39:44 --> Undefined index: id
in APPPATH\Controllers\Director.php on line 75.
 1 APPPATH\Controllers\Director.php(75): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: id', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 75, [])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->eliminar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:57:52 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:57:55 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:58:31 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:58:44 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:58:47 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:58:55 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:59:25 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:59:38 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:59:42 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:59:51 --> Undefined offset: 0
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offset: 0', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 21:59:53 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:00:21 --> Call to a member function getResult() on array
in APPPATH\Controllers\Director.php on line 98.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:00:22 --> Call to a member function getResult() on null
in APPPATH\Controllers\Director.php on line 98.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:00:49 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:00:51 --> Undefined offset: 0
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offset: 0', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:01:25 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 114.
 1 APPPATH\Controllers\Director.php(114): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 114, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:01:28 --> Undefined offset: 0
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offset: 0', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:02:07 --> Undefined offset: 0
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offset: 0', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:02:12 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 114.
 1 APPPATH\Controllers\Director.php(114): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 114, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:03:29 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 114.
 1 APPPATH\Controllers\Director.php(114): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 114, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:05:48 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 114.
 1 APPPATH\Controllers\Director.php(114): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 114, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:05:55 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 114.
 1 APPPATH\Controllers\Director.php(114): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 114, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:05:58 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 102.
 1 APPPATH\Controllers\Director.php(102): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 102, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:06:45 --> syntax error, unexpected 'echo' (T_ECHO)
in APPPATH\Controllers\Director.php on line 100.
 1 SYSTEMPATH\Router\Router.php(507): CodeIgniter\Router\AutoRouter->getRoute('director/actualizar')
 2 SYSTEMPATH\Router\Router.php(206): CodeIgniter\Router\Router->autoRoute('director/actualizar')
 3 SYSTEMPATH\CodeIgniter.php(815): CodeIgniter\Router\Router->handle('director/actualizar')
 4 SYSTEMPATH\CodeIgniter.php(449): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:06:47 --> syntax error, unexpected 'echo' (T_ECHO)
in APPPATH\Controllers\Director.php on line 100.
 1 SYSTEMPATH\Router\Router.php(507): CodeIgniter\Router\AutoRouter->getRoute('director/actualizar')
 2 SYSTEMPATH\Router\Router.php(206): CodeIgniter\Router\Router->autoRoute('director/actualizar')
 3 SYSTEMPATH\CodeIgniter.php(815): CodeIgniter\Router\Router->handle('director/actualizar')
 4 SYSTEMPATH\CodeIgniter.php(449): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:06:56 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:07:09 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:07:15 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:07:17 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:07:42 --> Cannot use object of type stdClass as array
in APPPATH\Controllers\Director.php on line 99.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:07:43 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:08:36 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:08:50 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:08:56 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:09:00 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:09:01 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:09:02 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:09:02 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:09:03 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:09:59 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:11:54 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:11:57 --> Trying to get property 'usuario_idusuario' of non-object
in APPPATH\Controllers\Director.php on line 99.
 1 APPPATH\Controllers\Director.php(99): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get property \'usuario_idusuario\' of non-object', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 99, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-21 22:12:39 --> Undefined variable: iddirector
in APPPATH\Controllers\Director.php on line 115.
 1 APPPATH\Controllers\Director.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: iddirector', 'C:\\xampp\\htdocs\\siera\\app\\Controllers\\Director.php', 115, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Director->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Director))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
